[versions]
agp = "8.5.1"
cardview = "1.0.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.6.1"
material = "1.10.0"
activity = "1.9.0"
constraintlayout = "2.1.4"
legacySupportV4 = "1.0.0"
lifecycleLivedataKtx = "2.8.4"
lifecycleViewmodelKtx = "2.8.4"
media3Exoplayer = "1.4.0"
navigationFragment = "2.7.7"
navigationUi = "2.7.7"
navigationRuntime = "2.7.7"
media3ExoplayerHls = "1.4.0"
volley = "1.2.1"
media3Session = "1.4.0"
comChaquoPythonGradlePlugin = "15.0.1"
gradle = "15.0.1"

[libraries]
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacySupportV4" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Exoplayer" }
media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3Exoplayer" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Exoplayer" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
navigation-runtime = { group = "androidx.navigation", name = "navigation-runtime", version.ref = "navigationRuntime" }
media3-exoplayer-hls = { group = "androidx.media3", name = "media3-exoplayer-hls", version.ref = "media3ExoplayerHls" }
volley = { group = "com.android.volley", name = "volley", version.ref = "volley" }
media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "media3Session" }
com-chaquo-python-gradle-plugin = { group = "com.chaquo.python", name = "com.chaquo.python.gradle.plugin", version.ref = "comChaquoPythonGradlePlugin" }
gradle = { group = "com.chaquo.python", name = "gradle", version.ref = "gradle" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

